import Head from 'next/head'
import { useForm } from 'react-hook-form'
import * as yup from 'yup'
import { LoginForm } from '../src/types/User';
import { yupResolver } from '@hookform/resolvers/yup';
import { Box, Flex, Text, FormControl, FormLabel, Input, FormErrorMessage, Button } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import { UserService } from '../src/services/UserService';
import { AxiosError } from 'axios';

const Home: React.FC = () => {
  const schema = yup.object().shape({
    email: yup.string().required(),
    password: yup.string().required(),
  })

  const { register, handleSubmit, formState: { errors } } = useForm<LoginForm>({
    resolver: yupResolver(schema),
  })

  const onSubmit = async (form: LoginForm) => {
    try {
      const res = await UserService.login({ data: form })
      console.log(res)
    } catch(e) {
      if (e instanceof AxiosError) {
        console.log(e.response?.data?.message)
      }
    }
  }

  return (
    <Box>
      <Text textAlign='center'>ログインページ</Text>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={styles.container}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Flex flexDirection='column' alignItems='center' mt={5}>
            <FormControl isInvalid={!!errors.email}>
              <FormLabel htmlFor='email' fontSize={'12px'}>メールアドレス</FormLabel>
              <Input {...register('email')}/>
              <FormErrorMessage>{errors.email?.message}</FormErrorMessage>
            </FormControl>
            <FormControl isInvalid={!!errors.password} mt={5}>
              <FormLabel htmlFor='password' fontSize={'12px'}>パスワード</FormLabel>
              <Input {...register('password')} type='password'/>
              <FormErrorMessage>{errors.password?.message}</FormErrorMessage>
            </FormControl>
            <Button type='submit' w={'50%'} mt={5}>ログイン</Button>
          </Flex>
        </form>
      </Box>
    </Box>
  )
}

export default Home